[project]
name = "agentic-local-n8n-v1-65-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["tomlkit>=0.13.2"]

[dependency-groups]
dev = ["black>=25.12.0", "isort>=7.0.0", "mypy>=1.19.1"]
