[project]
name = "ni8mare"
version = "0.1.0"
description = "Exploitation script for CVE-2026-21877 (n8n)"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "requests>=2.31.0",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "types-requests>=2.32.4.20260107",
]
